### PR TITLE
fix(frontend): add base to index.html to properly react to reverse proxies

### LINKED ISSUE #36: [Enhancement] Ingress support
Just throwing a suggestion out there that it would be good if the web portal was accessble using HA ingress.

### PR DESCRIPTION
**Pull request by t0bst4r**
fixes #36 
related to #98

### CODE REVIEW

File: packages/backend/src/api/web-ui.ts [hunk 1]
```diff
@@ -1,16 +1,17 @@
...
     router.get(/.*/, (req: express.Request, res: express.Response) => {
-      if (fs.existsSync(path.join(dist, req.path))) {
-        res.sendFile(path.join(dist, req.path));
-      } else {
-        res.sendFile(path.join(dist, "index.html"));
-      }
+      const relative = path.relative(path.join(dist, req.path), dist);
+      const content = fs
+        .readFileSync(path.join(dist, "index.html"), "utf8")
+        .replace("<!-- BASE -->", `<base href='${relative}' />`);
```
Comment (t0bst4r) [inline packages/backend/src/api/web-ui.ts:13]: This will work as long as it is not proxied with a sub-path.

Comment (t0bst4r) [reply packages/backend/src/api/web-ui.ts:13]: See https://developers.home-assistant.io/docs/add-ons/presentation/#ingress
